name: Salesforce CI (Ant migration tool)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Validata with ant
      run: ant validate -Dsf.username=${{secrets.SALESFORCE_USERNAME}} -Dsf.password=${{secrets.SALESFORCE_PASSWORD}}
