name: Salesforce CI (Ant migration tool)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      sf_username:
        description: 'Salesforce Username'
        required: false
      sf_password:
        description: 'Salesforce Password'
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: DEBUG Echo out a GitHub Actions Secret to the logs
      run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{ secrets.SALESFORCE_USERNAME }}
        echo "Trick to echo GitHub Actions Secret:  "
        echo ${{ secrets.SALESFORCE_USERNAME }} | sed 's/./& /g'
        
    - name: Validate with ant
      env:
        SF_USERNAME: ${{ github.event.inputs.sf_username || secrets.SALESFORCE_USERNAME }}
        SF_PASSWORD: ${{ github.event.inputs.sf_password || secrets.SALESFORCE_PASSWORD }}
      run: ant validate -Dsf.username=${SF_USERNAME} -Dsf.password=${SF_PASSWORD}
